services:
  nginx-php-fpm-app:
    image: tiredofit/nginx-php-fpm/8.3-alpine
    container_name: nginx-php-fpm-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-php-fpm-app.rule=Host(`nginx.example.com`)
      - traefik.http.services.nginx-php-fpm-app.loadbalancer.server.port=80
    volumes:
      - ./data/:/www/html
      - ./logs/:/www/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=nginx-php-fpm-app-app
    networks:
      - services
      - proxy
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true

